// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlzeyzexqkqojmwarwbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsemV5emV4cWtxb2ptd2Fyd2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDYwNDMsImV4cCI6MjA3MDYyMjA0M30.u20ZzhZKkIkME3Zmg8DXOKiRchYT5LSZwA5WcKGQGD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});